#!/bin/bash

./clean

./comp

##compOK=`tail -1 comp.log | grep -c OK `
compOK=`grep -c 'Tnum OK' comp.log `

if [ $compOK = '1' ]
then
 echo " Tnum compilation: OK"
else
 echo " Tnum compilation: ERROR"
 exit
fi



i=0
for dat in dat*
do
#  echo Tnum test: $dat
  ./$dat | LANG=c awk -f err_ana.awk >> err_Tnum
  tail -1 err_Tnum
  i=$((i+1))
done

nb_err=`grep -c "ERROR(s)" err_Tnum `
echo "ERROR(s) in "$i"-Tnum tests:" $nb_err
