#!/bin/bash

test_size=$1

if [ -z $test_size ]
then
  test_size=small
fi

if [ $test_size = 'small' ]
then
 echo " Small tests"
fi

if [ $test_size = 'medium' ]
then
 echo " Medium tests"
fi

if [ $test_size = 'big' ]
then
 echo " Big tests"
fi


 SYSTEM=sub_system_HNO3_ccsdt_RPH.f


 cp HESS-fit/inter_0-vtz HESS-fit/inter_0

here=`pwd`

DIR_vib=../..
DIR_pot=$DIR_vib/sub_pot

 cp $SYSTEM $DIR_pot/sub_system.f

cd $DIR_vib
 make &> $here/comp.log
cd $here


./DAT_files/dat_HNO3_ccsdt-RPH 0 3 f
./CompareLevel res_HNO3_RPH_LB0-LG3 Table4_PCCP2010-1+8D.txt 3

if [ $test_size = 'medium' ]
then
 ./DAT_files/dat_HNO3_ccsdt-RPH 1 3 t
 ./DAT_files/dat_HNO3_ccsdt-RPH 2 4 t
 ./DAT_files/dat_HNO3_ccsdt-RPH 3 5 t
 ./CompareLevel res_HNO3_RPH_LB3-LG5 Table4_PCCP2010-1+8D.txt 4
fi

if [ $test_size = 'big' ]
then
 ./DAT_files/dat_HNO3_ccsdt-RPH 1 3 t
 ./DAT_files/dat_HNO3_ccsdt-RPH 2 4 t
 ./DAT_files/dat_HNO3_ccsdt-RPH 3 5 t
 ./CompareLevel res_HNO3_RPH_LB3-LG5 Table4_PCCP2010-1+8D.txt 4

 ./DAT_files/dat_HNO3_ccsdt-RPH 6 7 t
 ./CompareLevel res_HNO3_RPH_LB6-LG7 Table4_PCCP2010-1+8D.txt 5
fi

