#!/bin/bash

here=`pwd`
DIR_vib=$here/../..

cd $DIR_vib
  make --no-print-directory  PhysConst &> $here/comp.log
cd $here
compOK=`tail -1 comp.log | grep -c OK `

if [ $compOK = '1' ]
then
 echo " PhysConst.exe compilation: OK"
else
 echo " PhysConst.exe compilation: ERROR"
 exit
fi


PCEXE=$DIR_vib/PhysConst.exe

OldTestsDir=output_28nov2018

./clean

for dat_name in dat*
do
   res_name=`echo res_$dat_name | sed 's/dat_//'`
   echo $res_name
   $PCEXE < $dat_name > $res_name
done


for res_name in res*
do
   echo ---------------------------------------
   echo ----------- $res_name

   ./CompareMass  $res_name
   ./CompareConst $res_name

   echo ---------------------------------------
done

