#!/bin/ksh

      for f in *.f
      do
        echo =========================================================
        echo $f

        sed "s/Write(6/write(out_unitp/g" $f > $f.new
        mv $f.new $f
        echo =========================================================
      done
