#!/bin/bash

#
# You should get:
# the flexible results (column 3 of table II),              Lauvergnat et al, JCP, v116 (2002) p8560
# and the ones of                                           Gatti et al, J. Mol. Spectrosc. v181 (1997) p403
#
#

here=`pwd`
DIR_vib=$here/../..

cd $DIR_vib
 make &> $here/comp.log
cd $here

#MH=1837.10882307318116
#MD=3671.297316
#MN=25525.4342723654045
#MC=21874.1407256995735

#x1=0.538516066
#x2=0.461483933

pi=3.14159265358979323846264338327950288419716939937511d0

########################
# Here we must use the followin masses and conversion constants
# to reproduce Gatti et al results
########################
#&constantes inv_Name=1836152.701d0, auTOcm_inv=219474.8877d0 /
 MH=1836.152701
 MN=25706.13781
 MC=22033.83241
 x1=0.53846153
 x2=0.461538461
########################

RES=res_flex20


nice $DIR_vib/vib << ** > $RES
 &system popenmp=f printlevel=2 /
 &constantes inv_Name=1836152.701  auTOcm_inv=219474.8877 /
 &variables 
         zmat=T
         nat=4
         sym=T
         nrho=2
         Write_QMotions=f
         QMLib=t
 /
$MC
0.0     1
$MN     2  1
$MH     2 -1 3
sym  cos(a)      R     r    x    pi   dh
6
1      0.        0.  $x1    1.   0.   0.
2      0.        0.  $x2   -1.   0.   0.
3      0.        0.  0.     0.   1.   0.
4      0.        1.  0.     0.   0.   0.
5      1.        0.  0.     0.   0.   0.
6      0.        0.  0.     0.   0.   1.

 1 20  20    0 0 0
 0  2   3    0 0 0 ! QML mapping for the type20 coordinates
 &minimum pot0=-0.499465823200 QMLib=t /
.999d0
3.187
2.179
0.
$pi
0.0

 &potential  pot_name='HCN_Murrell' option=21 /
 Qdyn_TO_QQMLib 1

 &basis_nD iQact(1)=1 name="Pl0" nb=51 nq=80 /
 &inactives /
 &actives test=f comput_S=t /
 &analyse max_ana=40 print=f /
**

echo $RES

egrep 'lev0:    1 |lev0:    2 |lev0:    3 |lev0:    5 '  $RES | awk '{print $5}' > lev_$RES
