#!/bin/bash

#
# You should get the E^h_exact results (column 4 of table II), Lauvergnat et al, JCP, v114 (2001) p6592
#

max_excit=$1
if [ -z $max_excit ]
then
  max_excit=11
fi

here=`pwd`
DIR_vib=$here/../..


 MH=1837.10882307318116
 MD=3671.297316
 MN=25525.4342723654045
 MC=21874.1407256995735

 x1=0.538516066
 x2=0.461483933

pi=3.14159265358979323846264338327950288419716939937511d0


RES=res_cHAC_HarD


nice $DIR_vib/vib << ** > $RES
 &system popenmp=f printlevel=2 /
 &constantes mass_version='HANDBOOK70ED' version='PUBLI2001' /
 &variables 
         zmat=T
         nat=4
         sym=T
         nrho=2
         Write_QMotions=f
         QMLib=t
 /
$MC
0.0     1
$MN     2  1
$MH     2 -1 3
sym  cos(a)      R     r    x    pi   dh
6
1      0.        0.  $x1    1.   0.   0.
2      0.        0.  $x2   -1.   0.   0.
3      0.        0.  0.     0.   1.   0.
4      0.        1.  0.     0.   0.   0.
5      1.        0.  0.     0.   0.   0.
6      0.        0.  0.     0.   0.   1.

 1 21  21    0 0 0
 0  2   3    0 0 0 ! QML mapping for the Qop20(Qact) functions
 &minimum pot0=-0.499465823200 HarD=t QMLib=t /
.999d0
3.187
2.179
0.
$pi
0.0

 &potential  pot_name='HCN_Murrell' option=21 /
 Qdyn_TO_QQMLib 1

 &basis_nD iQact(1)=1 name="Pl0" nb=51 nq=80 /
 &inactives
           max_excit=$max_excit
           tab_nq(1:2)=16,16
           isort=2
           step=0.0001
/
 &actives test=f comput_S=t /
 &analyse max_ana=40 print=f /
**

echo $RES

 egrep 'lev0:    1 |lev0:    2 |lev0:    4 |lev0:    8 '  $RES  | awk '{print $6}' > lev_$RES
