#!/bin/bash

#
# You should get:
# the rigid results (column 2 of table II),              Lauvergnat et al, JCP, v116 (2002) p8560
#
#

here=`pwd`
DIR_vib=$here/../..

cd $DIR_vib
 make &> $here/comp.log
cd $here


 MH=1837.10882307318116
 MD=3671.297316
 MN=25525.4342723654045
 MC=21874.1407256995735

 x1=0.538516066
 x2=0.461483933

pi=3.14159265358979323846264338327950288419716939937511d0

RES=res_rigid0


nice $DIR_vib/vib << ** > $RES
 &system popenmp=f printlevel=2 /
 &constantes mass_version='HANDBOOK70ED' version='PUBLI2001' /
 &variables 
         zmat=T
         nat=4
         sym=T
         nrho=2
         Write_QMotions=f
 /
$MC
0.0     1
$MN     2  1
$MH     2 -1 3
sym  cos(a)      R     r    x    pi   dh
6
1      0.        0.  $x1    1.   0.   0.
2      0.        0.  $x2   -1.   0.   0.
3      0.        0.  0.     0.   1.   0.
4      0.        1.  0.     0.   0.   0.
5      1.        0.  0.     0.   0.   0.
6      0.        0.  0.     0.   0.   1.

 1  0   0    0 0 0
 &minimum pot0=-0.499465823200 QMLib=t /
.999d0
3.187
2.179
0.
$pi
0.0

 &potential  pot_name='HCN_Murrell' option=21 /
 Qdyn_TO_QQMLib 1

 &basis_nD iQact(1)=1 name="Pl0" nb=51 nq=80 /
 &inactives /

 &actives test=f comput_S=t /
 &analyse max_ana=40 print=f /
**

echo $RES

egrep 'lev0:    1 |lev0:    2 |lev0:    3 |lev0:    5 '  $RES | awk '{print $5}' > lev_$RES
