#!/bin/ksh

 ici=`pwd`
 cd ../..
 make tnum-dist
 cd $ici

../../Tnum90.exe << ** > res
 &variables zmat=T nat=3 /
O
H 1
H 1 2

1  1 1
 &minimum read_nameQ=t unit='angs' /
 R1 0.9894120
 R2 0.9894120
 A 100.0269146

 &calculation calc_GG=t /
**
